import Head from 'next/head';
import type { ReactNode, ReactElement } from 'react';
import Header from '@components/header/Header';
import Footer from '@components/footer/Footer';

type Props = {
  children: ReactNode;
};

function Layout(props: Props): ReactElement {
  return (
    <>
      <Head>
        <title>哔哩哔哩 (゜-゜)つロ 干杯~-bilibili</title>
        <meta name="title" content="哔哩哔哩 (゜-゜)つロ 干杯~-bilibili" />
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, user-scalable=no"
        ></meta>
        <link
          rel="icon"
          href={`${process.env.NEXT_PUBLIC_BASE_URL}/favicon.ico`}
        />
      </Head>
      <Header />
      {props.children}
      <Footer />
    </>
  );
}

export default Layout;
