import React, { useEffect } from 'react';
import Head from 'next/head';
import { Provider } from 'react-redux';
import store from '@/store/index';
import screenAdapter from '@/utils/screen-adapter';
import type { NextPage } from 'next';
import type { AppProps } from 'next/app';
import '@/styles/global.css';
import '@/styles/font.css';
import '@/styles/not-found.scss';

type NextPageWithLayout<P = {}, IP = P> = NextPage<P, IP> & {
  getLayout?: (page: React.ReactElement) => React.ReactNode;
};

type AppPropsWithLayout = AppProps & {
  Component: NextPageWithLayout;
};

function MyApp({
  Component,
  pageProps
}: AppPropsWithLayout): React.ReactElement {
  // 屏幕适配
  useEffect(() => {
    screenAdapter();
    window.addEventListener('resize', screenAdapter);

    return () => {
      window.removeEventListener('resize', screenAdapter);
    };
  }, []);

  // 每页布局
  const getLayout = Component.getLayout || (page => page);

  return (
    <Provider store={store}>
      <Head>
        <title>哔哩哔哩 (゜-゜)つロ 干杯~-bilibili</title>
        <meta name="title" content="哔哩哔哩 (゜-゜)つロ 干杯~-bilibili" />
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, user-scalable=no"
        ></meta>
        {/* 解决视频链接403问题 */}
        <meta name="referrer" content="never"></meta>
        <link
          rel="icon"
          href={`${process.env.NEXT_PUBLIC_BASE_URL}/favicon.ico`}
        />
      </Head>
      {getLayout(<Component {...pageProps} />)}
    </Provider>
  );
}

export default MyApp;
